#!/usr/bin/env bash
# disable-readonly-root.sh — rollback twin of enable-readonly-root.sh
# (Module A, issue #16 Track 3: every field op needs a way back).
# Repo path : raspberry/hardening/disable-readonly-root.sh
# Run ON THE PI as root:  sudo raspberry/hardening/disable-readonly-root.sh
# then REBOOT (the overlay ends with the boot that loaded it; removing the
# artifacts only stops FUTURE boots from stacking it).
#
# Modes:
#   (no args)      apply (root): remove the init-bottom script, the kernel-
#                  upgrade hook, the initramfs image, the config.txt line and
#                  the modules line. Idempotent: an already-disabled node is
#                  a clean no-op.
#   --dry-run      print every step verbatim, write nothing (rootless-safe)
#   --status       report whether the read-only root is configured/active
#                  (rootless-safe; exit 0 always)
#
# NOT removed on purpose: the .dtn-bak backups created by the enable path —
# they are byte-identical stock files in the worst case and the operator's
# escape hatch in the interesting case. Removal is three markers + one image
# + two scripts; anything else on the box stays exactly as it was.
#
# WHY THE DATA-DIR BIND-MOUNT MATTERS HERE TOO: while the overlay is ACTIVE,
# durable changes only survive if made through the documented remount cycle
# (enable-readonly-root.sh header, "field-ops trade-off"). This script is the
# first half of that cycle — after the reboot the root is the plain ext4
# filesystem again and configuration changes persist as usual.

set -euo pipefail

# Environment overrides — MUST mirror enable-readonly-root.sh (tests point
# both at the same scratch tree).
BOOT_DIR="${BOOT_DIR:-$([ -d /boot/firmware ] && echo /boot/firmware || echo /boot)}"
INITRAMFS_SCRIPT="${INITRAMFS_SCRIPT:-/usr/share/initramfs-tools/scripts/init-bottom/dtn-overlayroot}"
POST_UPDATE_HOOK="${POST_UPDATE_HOOK:-/etc/initramfs/post-update.d/dtn-overlayroot-regen}"
MODULES_FILE="${MODULES_FILE:-/etc/initramfs-tools/modules}"
INITRAMFS_IMG_NAME="initramfs-dtn"
CONFIG_TXT="${CONFIG_TXT:-$BOOT_DIR/config.txt}"

CONFIG_MARKER="# --- dtn-node read-only-root snippet (added by enable-readonly-root.sh) ---"
MODULE_MARKER="# added by enable-readonly-root.sh: the init-bottom overlay needs this in the initramfs"

MODE="apply"
for arg in "$@"; do
    case "$arg" in
        --dry-run) MODE="dry-run" ;;
        --status)
            # Keep --status byte-identical to the enable twin's answer: the
            # repo keeps both scripts side by side under their plain names,
            # the provisioned box under the dtn- prefix — first that exists.
            here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
            enable="$here/enable-readonly-root.sh"
            [ -f "$enable" ] || enable="$here/dtn-enable-readonly-root.sh"
            exec "$enable" --status
            ;;
        -h | --help)
            sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^$/d; /Modes:/q' | head -n 14
            exit 0
            ;;
        *)
            echo "disable-readonly-root: ERROR: unknown option '$arg' (usage: disable-readonly-root.sh [--dry-run|--status])" >&2
            exit 1
            ;;
    esac
done

log() { echo "disable-readonly-root: $*"; }
die() { echo "disable-readonly-root: ERROR: $*" >&2; exit 1; }

if [ "$MODE" = "dry-run" ]; then
    log "[dry-run] would remove the init-bottom script $INITRAMFS_SCRIPT"
    log "[dry-run] would remove the kernel-upgrade hook $POST_UPDATE_HOOK"
    log "[dry-run] would delete the initramfs image $BOOT_DIR/$INITRAMFS_IMG_NAME"
    log "[dry-run] would remove the config.txt snippet (marker + initramfs line) from $CONFIG_TXT"
    log "[dry-run] would remove the overlay line + marker from $MODULES_FILE"
    log "[dry-run] takes effect at the next REBOOT (an active overlay lives until the current boot ends)"
    exit 0
fi

[ "$(id -u)" -eq 0 ] || die "must run as root (removes initramfs artifacts and edits the boot partition); try --dry-run or --status"

removed=0

# Refuse to touch a foreign file (mirror of the enable-side guard).
for target in "$INITRAMFS_SCRIPT" "$POST_UPDATE_HOOK"; do
    if [ -f "$target" ] && ! grep -q "Generated by raspberry/hardening/enable-readonly-root.sh" "$target"; then
        die "$target was not generated by enable-readonly-root.sh — refusing to delete a foreign file"
    fi
done

if [ -f "$INITRAMFS_SCRIPT" ]; then
    rm -f "$INITRAMFS_SCRIPT"
    log "removed $INITRAMFS_SCRIPT"
    removed=1
fi
if [ -f "$POST_UPDATE_HOOK" ]; then
    rm -f "$POST_UPDATE_HOOK"
    log "removed $POST_UPDATE_HOOK"
    removed=1
fi
if [ -f "$BOOT_DIR/$INITRAMFS_IMG_NAME" ]; then
    rm -f "$BOOT_DIR/$INITRAMFS_IMG_NAME"
    log "removed $BOOT_DIR/$INITRAMFS_IMG_NAME"
    removed=1
fi
if [ -f "$CONFIG_TXT" ] && grep -qxF "$CONFIG_MARKER" "$CONFIG_TXT"; then
    cp -a "$CONFIG_TXT" "$CONFIG_TXT.dtn-bak"
    # Remove exactly the two lines the enable path appended (whole-line,
    # fixed-string matches — nothing else in the firmware config is touched;
    # the snippet's leading blank line stays, which config.txt tolerates).
    awk -v marker="$CONFIG_MARKER" \
        -v line="initramfs $INITRAMFS_IMG_NAME followkernel" \
        '$0 != marker && $0 != line { print }' "$CONFIG_TXT" > "$CONFIG_TXT.tmp"
    mv "$CONFIG_TXT.tmp" "$CONFIG_TXT"
    if grep -qxF "$CONFIG_MARKER" "$CONFIG_TXT"; then
        die "post-check failed: config.txt still carries the marker"
    fi
    log "removed the config.txt snippet (backup: $CONFIG_TXT.dtn-bak)"
    removed=1
fi
if [ -f "$MODULES_FILE" ] && grep -qxF "$MODULE_MARKER" "$MODULES_FILE"; then
    cp -a "$MODULES_FILE" "$MODULES_FILE.dtn-bak"
    # Whole-line fixed matches: the marker and the bare 'overlay' module line
    # (the only overlay entry in the file is the one the enable path added).
    awk -v marker="$MODULE_MARKER" '$0 != marker && $0 != "overlay" { print }' \
        "$MODULES_FILE" > "$MODULES_FILE.tmp"
    mv "$MODULES_FILE.tmp" "$MODULES_FILE"
    if grep -qxF "$MODULE_MARKER" "$MODULES_FILE"; then
        die "post-check failed: $MODULES_FILE still carries the marker"
    fi
    log "removed the overlay module line from $MODULES_FILE"
    removed=1
fi

if [ "$removed" = "0" ]; then
    log "nothing to do: the read-only root is not configured (already disabled)"
else
    log "OK — DISABLED. Take effect at the next reboot ('sudo reboot')."
    log "Verify afterwards: disable-readonly-root.sh --status (root must show as ext4, not overlay)"
fi
